# Generated by Django 3.0.2 on 2020-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('active', models.CharField(blank=True, max_length=10, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('wiki', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('apple', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
                ('amazon', models.URLField(blank=True, null=True)),
                ('spotify', models.URLField(blank=True, null=True)),
                ('soundcloud', models.URLField(blank=True, null=True)),
                ('bandcamp', models.URLField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
