# Generated by Django 3.0.2 on 2020-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='active',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
