# Generated by Django 3.0.2 on 2020-02-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0003_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='youtube_ids',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
