# Generated by Django 3.0.2 on 2020-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0004_disc_youtube_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disc',
            name='youtube_ids',
        ),
        migrations.AddField(
            model_name='disc',
            name='video_ids',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
