# Generated by Django 3.0.2 on 2020-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0005_auto_20200202_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disc',
            name='video_ids',
        ),
        migrations.AddField(
            model_name='disc',
            name='youtube_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
