# Generated by Django 3.0.2 on 2020-02-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0006_auto_20200202_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disc',
        ),
    ]
