# Generated by Django 3.0.2 on 2020-02-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0008_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='bands',
            field=models.ManyToManyField(to='grock.Band'),
        ),
    ]
