# Generated by Django 3.0.2 on 2020-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0011_auto_20200208_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='release_band',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
