# Generated by Django 3.0.2 on 2020-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0012_disc_release_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='coverd_bands',
            field=models.ManyToManyField(blank=True, related_name='coverd_discs', to='grock.Band'),
        ),
    ]
