# Generated by Django 3.0.2 on 2020-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0013_disc_coverd_bands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='bands', to='grock.Genre'),
        ),
        migrations.AddField(
            model_name='disc',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='discs', to='grock.Genre'),
        ),
    ]
