# Generated by Django 3.0.2 on 2020-02-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grock', '0014_auto_20200208_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ForeignKey(blank=True, default='pop_punk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grock.Genre'),
        ),
    ]
