source "http://rubygems.org"

gem "rake"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-activerecord"
gem "activesupport"
gem "sqlite3"
gem "opal"
gem "countries"
gem "sassc"
gem "simple-rss"
gem "pry-byebug"
