version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: ./manage.py build
      - run: git config user.email "circleci@users.noreply.github.com"
      - run: git config user.name "circleci"
      - run: git add docs
      - run: git commit -m 'add build results'
      - run: git push origin master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build