source "https://rubygems.org"

ruby "2.3.0"

gem 'rake'
gem 'dotenv'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'activesupport'
gem 'config'
gem 'google_custom_search_api'

gem 'httpclient'
gem 'redcarpet'

group :development do
  gem 'sqlite3'
  gem 'sinatra-contrib'
  gem 'pry-byebug'
end

group :production do
  gem 'pg'
end

group :test do
  gem 'minitest-power_assert'
  gem 'factory_girl'
  gem 'database_cleaner'
  gem 'simplecov'
end
